<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Teliki.Core\Teliki.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="appsettings.ini" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
